cooommmmit
lDagothUrl/java-shareit pull request #3
Opened 2023-11-02 23:53 UTC by lDagothUrl

2023-11-04 01:45 UTC, NikolaiDem requested changes
Необходимо починить сборку

2023-11-05 11:06 UTC, NikolaiDem requested changes

2023-11-05 11:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.error("Validation {}", e.getMessage());
Чтобы сохранять и стектрейс, можно использовать такой метод
        log.error("Validation {}", e.getMessage(), e);

2023-11-05 11:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final ItemService userMapper = new ItemService();
Почему userMapper  ?

2023-11-05 11:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item postItem(@RequestBody Item item, @NotNull @RequestHeader("X-Sharer-User-Id") Integer owner) {
Вынести "X-Sharer-User-Id" в константы

2023-11-05 11:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item getItem(@PathVariable(value = "itemId") Integer itemId, @NotNull @RequestHeader("X-Sharer-User-Id") Integer owner) {
owner должен использоваться для проверки существования юзера и его прав доступа к предмету
Аналогично для следующего метода

2023-11-05 11:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/repository/MemoryItem.java
> +            if (item.getAvailable() && itemStr.contains(text)) {
Пусть name - это aa, description - bb, text - ab. По логике этого метода он ничего вернуть не должен, а по факту совпадение будет найдено

2023-11-05 11:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/repository/MemoryItem.java
> +            if (itemOwner == owner) {
Логика проверки прав доступа должна быть в сервисе

2023-11-05 11:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        Item itemMap = memoryItem.getItem(id);
itemMap мапой не является

2023-11-05 11:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        if (MemoryUser.getUser(owner) == null) {
Методы репозитория не должны быть статическими

2023-11-05 11:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item postItem(@RequestBody Item item, @NotNull @RequestHeader("X-Sharer-User-Id") Integer owner) {
Методы контроллера должны принимать и возвращать dto классы.
Аналогично для остальных контроллеров

2023-11-05 11:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/repository/MemoryUser.java
> +        return userMap.size() == 0 ? new ArrayList<>() : new ArrayList<>(userMap.values());
Условие лишнее

2023-11-05 11:06 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/service/ServiceUser.java
> +        User userMap = memoryUser.getUser(id);
user

2023-11-05 13:59 UTC, lDagothUrl commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item getItem(@PathVariable(value = "itemId") Integer itemId, @NotNull @RequestHeader("X-Sharer-User-Id") Integer owner) {
Все замечательно, но тогда не проходит валидацию постман.

2023-11-05 19:08 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item getItem(@PathVariable(value = "itemId") Integer itemId, @NotNull @RequestHeader("X-Sharer-User-Id") Integer owner) {
Как были реализованы проверки?Какие тесты из постмана не проходят?

2023-11-06 12:54 UTC, NikolaiDem requested changes

2023-11-06 12:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto postItem(@RequestBody Item item, @NotNull @RequestHeader("X-Sharer-User-Id") final Integer owner) {
В RequestBody тоже должен быть ItemDto

2023-11-06 12:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto putItem(@PathVariable int id, @RequestBody Item item, @NotNull @RequestHeader("X-Sharer-User-Id") final Integer owner) {
В RequestBody тоже должен быть ItemDto

2023-11-06 12:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/ItemDto.java
> +    @JsonProperty
Для чего здесь эта аннотация?

2023-11-06 12:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    private final MemoryItem memoryItem;
Для репозиториев лучше создать интерфейсы, чтобы не зависеть от реализации

2023-11-06 12:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto putUser(@PathVariable int id, @RequestBody User user) {
Вместо User лучше указать UserDto, чтобы придерживаться разделения слоев .
Аналогично для postUser

2023-11-06 12:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/service/ServiceUser.java
> +public class ServiceUser {
ItemService, но ServiceUser. Лучше придерживаться одинаковых правил именования

2023-11-06 12:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/service/ServiceUser.java
> +        if (userList.size() != 0) {
Эта проверка избыточна

2023-11-06 12:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/service/ServiceUser.java
> +        if (userList.size() != 0) {
Эта проверка избыточна

2023-11-06 12:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/repository/MemoryUser.java
> +    private static final Map<Integer, User> userMap = new HashMap<>();
static здесь не нужен. Если будет несколько репозиториев, то у каждого должны быть свои данные

2023-11-06 12:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    public ItemDto getItem(int id, int owner) {
Отсутствуют проверки owner.
Аналогично ниже

2023-11-06 12:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        return ++newId;
Генерация id - задача репозитория

2023-11-06 12:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/service/ServiceUser.java
> +    private int createId() {
Генерация id - задача репозитория

2023-11-06 12:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/service/ServiceUser.java
> +                    throw new RuntimeException("The user already exists");
Для ошибок бизнес логики лучше использовать кастомные исключения или соответствующее исключение из java.lang. Таким образом легче понять, что произошло, и корректно обработать в зависимости от его типа

2023-11-06 12:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/service/ServiceUser.java
> +    private void checkEmail(User user, int id) {
Практически полный дубль предыдущего метода

2023-11-07 22:49 UTC, NikolaiDem requested changes

2023-11-07 22:49 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return memoryItem.getItems().stream().filter(item -> item.getOwner() == owner).map(ItemMapper::itemToDto).collect(Collectors.toList());
Не нужно получать все items из репозитория, их может много, лучше сделать фильтр по owner в самом репозитории

2023-11-07 22:49 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto getItem(@PathVariable(value = "itemId") final Integer itemId, @NotNull @RequestHeader("X-Sharer-User-Id") final Integer owner) {
@NotNull @RequestHeader("X-Sharer-User-Id") final Integer owner не нужен вообще

2023-11-07 22:49 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> getItem(@RequestParam(value = "text") final String text, @NotNull @RequestHeader("X-Sharer-User-Id") final Integer owner) {
@NotNull @RequestHeader("X-Sharer-User-Id") final Integer owner не нужен вообще

2023-11-08 22:29 UTC, NikolaiDem approved these changes

2023-11-09 00:41 UTC, merged