add docker
lDagothUrl/java-shareit pull request #6
Opened 2023-11-23 14:35 UTC by lDagothUrl

2023-11-24 05:40 UTC, NikolaiDem requested changes

2023-11-24 05:40 UTC, NikolaiDem commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        try {
Статический метод с try/catch получения BookingState из строки необходимо перенести в класс BookingState, чтобы не дублировать блок try/catch.
Исправить и в остальных методах

2023-11-24 05:40 UTC, NikolaiDem commented on server/pom.xml
> +        <dependency>
В модуле server валидация не нужна

2023-11-24 05:40 UTC, NikolaiDem commented on server/src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +//        for (Request request : requestListMap.keySet()) {
Что ломается в такой реализации? И такую же реализацию нужно применить к
getAllItemRequests()

2023-11-24 13:38 UTC, lDagothUrl commented on server/src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +//        for (Request request : requestListMap.keySet()) {
запрос есть а айтема нет, тут мы и теряем значение

2023-11-25 13:34 UTC, NikolaiDem approved these changes

2023-11-25 13:34 UTC, NikolaiDem commented on server/src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +            requestListMap.put(request, null);
Эти действия лишние

2023-12-09 00:32 UTC, merged